spring:
  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:tcp://localhost:1521/shopping
    username: sa
    password:
    driver-class-name: org.h2.Driver

